// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhjqsfcqiabfqntmesle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoanFzZmNxaWFiZnFudG1lc2xlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mzc5NzMsImV4cCI6MjA2ODUxMzk3M30.5c8e5aUwO-zusGRG4uGA4yvNRXd86LByJGhtkUw8vo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});